version: '3'
services:
  frontend:
    image: cameliafarkas/idp:frontend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - "database"
  backend:
    image: cameliafarkas/idp:backend
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - "database"
  payment:
    image: cameliafarkas/idp:payment
    ports:
      - "4005:4005"
    restart: always
    depends_on:
      - "database"
  database:
    image: cameliafarkas/idp:database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: hairshop
    ports:
      - '3306:3306'
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - "database"
  #   networks:
  #     - application_network
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080/tcp"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
